# Numpy - Numerical Python

## 1. Ndarry (Numpy Dimensional Array)

In [5]:
# de facto standard
import numpy as np

In [8]:
a = np.array([1,4,5,8],float)
print(a)

[1. 4. 5. 8.]


In [9]:
a[3], a.dtype, a.shape

(8.0, dtype('float64'), (4,))

## 2. Array shape

In [11]:
# 1차원 - Vector
a = np.array([1,4,5,8],float)

In [14]:
# 2차원 - matrix
m = [[1,4],[5,8]]
b = np.array(m,float)
print(b)

[[1. 4.]
 [5. 8.]]


In [65]:
# 3차원 - tensor
t = [[[1, 4], [5, 8]], [[11, 14], [15, 18]]]
c = np.array(t, float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [19]:
a.shape, b.shape

((4,), (2, 2))

In [16]:
#ndim
a.ndim, b.ndim

(1, 2)

In [18]:
# size - element의 개수
a.size, b.size

(4, 4)

In [66]:
# data type(dtype)
c = np.array(t, dtype=np.float32)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]], dtype=float32)

## * reshape: size는 동일

In [67]:
c.reshape(2, 4).shape

(2, 4)

In [68]:

c.reshape(2, 4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [69]:
c.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

In [70]:
# -1은 한번만 사용 가능
c.reshape(-1, 4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [71]:
# flatten - 1차원으로 변환 flatten - 1차원으로 변환
c.flatten()
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

## 3. Indexing and Slicing

In [28]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
a[0][1], a[0,1]     # 행 인덱스, 열 인덱스

(1, 1)

In [31]:
a[:,:2]

array([[0, 1],
       [3, 4]])

In [43]:
b = np.arange(16).reshape(-4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
b[1:3,1:3]     #5,6,9,10 출력

array([[ 5,  6],
       [ 9, 10]])

In [44]:
b[:3,:2]        #0,1,4,5,8,9

array([[0, 1],
       [4, 5],
       [8, 9]])

In [48]:

# 세번째 열까지는 X< 마지막 열은 Y
X, Y = b[:,:-1],b[:,-1]
X.shape, Y.shape

((4, 3), (4,))

## 4. Creation

In [50]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
# 실수는 우리가 원하는 값을 정확하게 표현하지 못함
np.arange(0,1.1,0.1).tolist()[3] == 0.3

False

In [54]:
# 두 실수의 비교는 차이가 아주 작냐를 물어보는 것이 올바른 방법임
np.abs(np.arange(0,1.1,0.1).tolist()[3] == 0.3) < 1e-8

True

In [56]:
# ones, zeros, empty
a = np.zeros((5,),dtype=np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [58]:
b = np.ones((2,4),dtype=np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [59]:
np.empty((2,5))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [60]:
a = np.arange(24).reshape(4,-1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [61]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [62]:
# 단위 행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
# eye - 대각선이 1인 행렬
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [73]:
np.eye(N=3, M=5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [74]:
np.eye(3, 5, 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
# 정규 분포
np.random.normal(0,1,10).reshape(2,5)

array([[-0.07175173,  0.37757609,  1.8652374 , -2.09823297,  1.21463454],
       [-0.57220104, -0.18230546, -2.6179807 , -0.38104993,  0.55641835]])

In [64]:
#이항분포, 포아송(poisson)분포, t-분포(standard_t), F-분포(f)
np.random.binomial(100,0.5,10)

array([46, 51, 53, 44, 51, 41, 47, 49, 46, 46])